<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csp</string>
	</array>
	<key>name</key>
	<string>CSPm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(channel|assert)\b</string>
			<key>name</key>
			<string>keyword.other.csp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|-&gt;|\|~\||\[\]|\[FD=|\[\|\{|\}\|\]|\|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.csp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(STOP|SKIP)\b</string>
			<key>name</key>
			<string>constant.language.csp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[FD=)</string>
			<key>name</key>
			<string>keyword.operator.csp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(deadlock free)\b</string>
			<key>name</key>
			<string>support.function.csp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z][A-Za-z_1-9]*</string>
			<key>name</key>
			<string>entity.name.state.csp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.csp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(---*(?!([!#\$%&amp;\*\+\./&lt;=&gt;\?@\\\^\|\-~:]|[^[^\p{S}\p{P}]_"'\(\),;\[\]`\{}]))).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-dash.csp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.csp</string>
	<key>uuid</key>
	<string>af8f73cf-a7c8-49ef-8af4-271469fd70f7</string>
</dict>
</plist>
